# Generated by Django 3.2.7 on 2021-10-29 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0003_auto_20211029_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
    ]
