# Generated by Django 4.1.3 on 2022-11-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0008_auto_20220221_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
