# Generated by Django 4.1.4 on 2022-12-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0011_remove_user_bio_remove_user_email_remove_user_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='postal',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
