# Generated by Django 4.1.4 on 2022-12-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0014_remove_user_bio_remove_user_email_remove_user_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
