# Generated by Django 4.1.4 on 2022-12-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0016_nofacemaskimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nofacemaskimages',
            old_name='date_created',
            new_name='created',
        ),
    ]
