# Generated by Django 4.1.3 on 2023-02-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0019_remove_camera_camera_status_camera_enabled_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_ID', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateTimeField()),
                ('report_source_images_id', models.CharField(max_length=200, null=True)),
                ('report_source_images_count', models.IntegerField(null=True)),
                ('report_source_images_matched_count', models.IntegerField(null=True)),
                ('unknown_faces_count', models.IntegerField(null=True)),
                ('report_student_id', models.CharField(max_length=200, null=True)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='face_recognition',
        ),
        migrations.RemoveField(
            model_name='images',
            name='false_alarm',
        ),
        migrations.AddField(
            model_name='images',
            name='camera_source_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='matched_student_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='report_id',
            field=models.IntegerField(null=True),
        ),
    ]
