# Generated by Django 4.1.3 on 2023-02-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0021_reports_output_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='camera_source_id',
        ),
        migrations.AddField(
            model_name='images',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='source_ip_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
