# Generated by Django 4.1.7 on 2023-03-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0023_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTraniningImage',
            fields=[
                ('student_training_image_ID', models.AutoField(primary_key=True, serialize=False)),
                ('student_image_filename', models.CharField(max_length=200, null=True)),
                ('student_image_path', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('student_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cubaapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='ImageOutputImage',
            fields=[
                ('image_output_image_ID', models.AutoField(primary_key=True, serialize=False)),
                ('image_output_image_filename', models.CharField(max_length=200, null=True)),
                ('image_output_image_path', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('report_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cubaapp.reports')),
            ],
        ),
    ]
