# Generated by Django 4.1.7 on 2023-03-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0024_studenttraniningimage_imageoutputimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_class',
            new_name='student_contact',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_photo_filename',
            new_name='student_course',
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
