# Generated by Django 4.1.3 on 2023-03-03 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0025_rename_student_class_student_student_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageoutputimage',
            old_name='image_output_image_filename',
            new_name='image_output_filename',
        ),
        migrations.RenameField(
            model_name='imageoutputimage',
            old_name='image_output_image_path',
            new_name='source_image_filename',
        ),
        migrations.AddField(
            model_name='imageoutputimage',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cubaapp.student'),
        ),
    ]
