# Generated by Django 4.1.3 on 2023-03-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0027_rename_image_output_filename_imageoutputimage_image_output_image_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageoutputimage',
            old_name='image_output_image_filename',
            new_name='image_output_filename',
        ),
    ]
