# Generated by Django 4.1.7 on 2023-03-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0029_imageoutputimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageoutputimage',
            name='confidence',
            field=models.IntegerField(null=True),
        ),
    ]
